version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout 
      - run: go mod vendor 
      - run: go test -v -race $(go list ./... | grep -v /vendor/) -coverprofile=coverage.txt
      - run: bash <(curl -s https://codecov.io/bash) -t 701e86bd-1c7e-43ee-903d-f73944e464c0